
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Prasanna V

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: Its not who you are underneath, its what you do, defines you.
  author: Batman

# Set this to your main site title
# In the head - ff page doesnt have its own title,
# Site title will be used instead
title: World of Prasanna - Author Prasanna

# Description and title below nav in the header
punch-line: true

# Your logo for the header
logo:
  title: Prasanna
  subtitle: Developer

include:
  - pages

# Following needed for disqus integration
# Set your 'disqus' account name
disqus:

# Uncomment if deployed locally
# url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url:

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl:

# Change this to your google analytics ID
google_analytics: UA-84602255-1

# Contact form pupublic key
contact_PK: 26a37df6e654df5aa083068e0a6a439c

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 40

##########################################
#          Do not change these variables
##########################################

sass:
  sass_dir: _sass
sass:
    style: compressed

include:
  - pages

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file
  - jekyll-gist

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
